[project]
name = "sutraml"
version = "0.1.0"
description = "SutraML is an end-to-end machine learning toolkit for data preprocessing, missing value handling, outlier detection, feature engineering, feature selection, hyperparameter tuning, and automated EDA. Built to simplify and accelerate ML workflows with scalable, production-ready utilities for data scientists and ML engineers."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = []
